//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientFacturacion.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FacturacionMethods")]
    public interface FacturacionMethods {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/ValidateCredentials", ReplyAction="http://tempuri.org/FacturacionMethods/ValidateCredentialsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidateCredentials(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/ValidateCredentials", ReplyAction="http://tempuri.org/FacturacionMethods/ValidateCredentialsResponse")]
        System.Threading.Tasks.Task<bool> ValidateCredentialsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/UploadXML", ReplyAction="http://tempuri.org/FacturacionMethods/UploadXMLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UploadXML(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/UploadXML", ReplyAction="http://tempuri.org/FacturacionMethods/UploadXMLResponse")]
        System.Threading.Tasks.Task<bool> UploadXMLAsync(System.Xml.XmlNode xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/InvoicesFromXML", ReplyAction="http://tempuri.org/FacturacionMethods/InvoicesFromXMLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientFacturacion.ServiceReference1.factura InvoicesFromXML(string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/InvoicesFromXML", ReplyAction="http://tempuri.org/FacturacionMethods/InvoicesFromXMLResponse")]
        System.Threading.Tasks.Task<ClientFacturacion.ServiceReference1.factura> InvoicesFromXMLAsync(string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/DataTableInvoicesFromXML", ReplyAction="http://tempuri.org/FacturacionMethods/DataTableInvoicesFromXMLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DataTableInvoicesFromXML(string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/DataTableInvoicesFromXML", ReplyAction="http://tempuri.org/FacturacionMethods/DataTableInvoicesFromXMLResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DataTableInvoicesFromXMLAsync(string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/DataTableInvoicesByPeriodXML", ReplyAction="http://tempuri.org/FacturacionMethods/DataTableInvoicesByPeriodXMLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DataTableInvoicesByPeriodXML(string rfc, string periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/DataTableInvoicesByPeriodXML", ReplyAction="http://tempuri.org/FacturacionMethods/DataTableInvoicesByPeriodXMLResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DataTableInvoicesByPeriodXMLAsync(string rfc, string periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/DeleteXML_Record", ReplyAction="http://tempuri.org/FacturacionMethods/DeleteXML_RecordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteXML_Record(string InvoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacturacionMethods/DeleteXML_Record", ReplyAction="http://tempuri.org/FacturacionMethods/DeleteXML_RecordResponse")]
        System.Threading.Tasks.Task<bool> DeleteXML_RecordAsync(string InvoiceNumber);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class factura : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalDeFacturasField;
        
        private string nombreField;
        
        private double totalField;
        
        private double subTotalField;
        
        private double totalImpuestosTrasladadosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalDeFacturas {
            get {
                return this.totalDeFacturasField;
            }
            set {
                this.totalDeFacturasField = value;
                this.RaisePropertyChanged("TotalDeFacturas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("Total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double SubTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
                this.RaisePropertyChanged("SubTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double TotalImpuestosTrasladados {
            get {
                return this.totalImpuestosTrasladadosField;
            }
            set {
                this.totalImpuestosTrasladadosField = value;
                this.RaisePropertyChanged("TotalImpuestosTrasladados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FacturacionMethodsChannel : ClientFacturacion.ServiceReference1.FacturacionMethods, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacturacionMethodsClient : System.ServiceModel.ClientBase<ClientFacturacion.ServiceReference1.FacturacionMethods>, ClientFacturacion.ServiceReference1.FacturacionMethods {
        
        public FacturacionMethodsClient() {
        }
        
        public FacturacionMethodsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacturacionMethodsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturacionMethodsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturacionMethodsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateCredentials(string username, string password) {
            return base.Channel.ValidateCredentials(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateCredentialsAsync(string username, string password) {
            return base.Channel.ValidateCredentialsAsync(username, password);
        }
        
        public bool UploadXML(System.Xml.XmlNode xml) {
            return base.Channel.UploadXML(xml);
        }
        
        public System.Threading.Tasks.Task<bool> UploadXMLAsync(System.Xml.XmlNode xml) {
            return base.Channel.UploadXMLAsync(xml);
        }
        
        public ClientFacturacion.ServiceReference1.factura InvoicesFromXML(string rfc) {
            return base.Channel.InvoicesFromXML(rfc);
        }
        
        public System.Threading.Tasks.Task<ClientFacturacion.ServiceReference1.factura> InvoicesFromXMLAsync(string rfc) {
            return base.Channel.InvoicesFromXMLAsync(rfc);
        }
        
        public System.Data.DataSet DataTableInvoicesFromXML(string rfc) {
            return base.Channel.DataTableInvoicesFromXML(rfc);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DataTableInvoicesFromXMLAsync(string rfc) {
            return base.Channel.DataTableInvoicesFromXMLAsync(rfc);
        }
        
        public System.Data.DataSet DataTableInvoicesByPeriodXML(string rfc, string periodo) {
            return base.Channel.DataTableInvoicesByPeriodXML(rfc, periodo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DataTableInvoicesByPeriodXMLAsync(string rfc, string periodo) {
            return base.Channel.DataTableInvoicesByPeriodXMLAsync(rfc, periodo);
        }
        
        public bool DeleteXML_Record(string InvoiceNumber) {
            return base.Channel.DeleteXML_Record(InvoiceNumber);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteXML_RecordAsync(string InvoiceNumber) {
            return base.Channel.DeleteXML_RecordAsync(InvoiceNumber);
        }
    }
}
